/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package baitapio_02;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.lang.classfile.BufWriter;
import java.nio.Buffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author tpbdr
 */
public class QuanLyFile extends javax.swing.JFrame {
    private File logFile;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyFile.class.getName());

    /**
     * Creates new form QuanLyFile
     */
    public QuanLyFile() {
        
        initComponents();
    }
    private void openLog(){
        try {
            String fileName = "D:\\Tool\\NetsBean\\log";
        this.logFile = new File(fileName);
        if(!logFile.exists()){
            this.logFile.createNewFile();
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void writeLog(String msg){
        try {
            FileOutputStream fos = new FileOutputStream(this.logFile);
            OutputStreamWriter osw = new OutputStreamWriter(fos,StandardCharsets.UTF_8);
            BufferedWriter bw = new BufferedWriter(osw);
            LocalDate currentTime = LocalDate.now();
            String time = currentTime.format(DateTimeFormatter.ISO_DATE);
            String user = "USER";
            bw.append(time + " "+ user +" "+" msg");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFolder = new javax.swing.JLabel();
        jButtonChoose = new javax.swing.JButton();
        jTextFieldFolder = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonDetele = new javax.swing.JButton();
        jButtonRename = new javax.swing.JButton();
        jButtonMove = new javax.swing.JButton();
        jButtonCopy = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFolder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFolder.setText("Folder");

        jButtonChoose.setText("Choose");
        jButtonChoose.addActionListener(this::jButtonChooseActionPerformed);

        jTextFieldFolder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonDetele.setText("Delete");
        jButtonDetele.addActionListener(this::jButtonDeteleActionPerformed);

        jButtonRename.setText("Rename");
        jButtonRename.addActionListener(this::jButtonRenameActionPerformed);

        jButtonMove.setText("Move");
        jButtonMove.addActionListener(this::jButtonMoveActionPerformed);

        jButtonCopy.setText("Copy");
        jButtonCopy.addActionListener(this::jButtonCopyActionPerformed);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(this::exitMenuItemActionPerformed);
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMove, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRename, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDetele, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabelFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldFolder)
                    .addComponent(jButtonChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRename)
                    .addComponent(jButtonDetele)
                    .addComponent(jButtonMove)
                    .addComponent(jButtonCopy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jButtonChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            jTextFieldFolder.setText(path);
            jTextArea1.setText(listAllFiles(path,0));
        }
        writeLog("Mo "+jTextFieldFolder.getText());
    }//GEN-LAST:event_jButtonChooseActionPerformed

    private void jButtonDeteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeteleActionPerformed
        int choose = JOptionPane.showConfirmDialog(this, "Are you sure delete all items");
        //Neu khong dong y xoa thi dung
        if (choose == JOptionPane.NO_OPTION){
            return;
        }
        try {
            String path = jTextFieldFolder.getText();
            File myFile = new File(path);
            deleteFile(path);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonDeteleActionPerformed

    private void jButtonRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameActionPerformed
        String newFileName = JOptionPane.showInputDialog(this,"Nhap ten file ");
        try {
            File myFile = new File(jTextFieldFolder.getText());
            String newPath = myFile.getParent() + "\\" + newFileName;
            File newFile = new File(newPath);
            if(myFile.renameTo(newFile)){
                JOptionPane.showMessageDialog(this, "Da doi ten thanh cong");
            }else{
                JOptionPane.showMessageDialog(this, "Khong the doi ten file");
            }
            jTextFieldFolder.setText(newPath);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonRenameActionPerformed

    private void jButtonMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMoveActionPerformed

    private void jButtonCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            String source = jTextFieldFolder.getText();
            Path sourcePath = Path.of(source);
            String destination = chooser.getSelectedFile().getAbsolutePath();
            Path destinationPath = Path.of(destination);
            try {
                copy(source, destination);
                JOptionPane.showMessageDialog(this, "Copy thanh cong");
     
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Copy khong thanh cong");
            }
            
        }
    }//GEN-LAST:event_jButtonCopyActionPerformed
    private void copy(String source, String destination){
        try {
            Path sourcePath = Path.of(source);
            Path destinationPath = Path.of(destination);
            Path newPath = destinationPath.resolve(sourcePath.getFileName());
            
            Files.copy(sourcePath, newPath ,StandardCopyOption.COPY_ATTRIBUTES);
            File myFile = new File(source);
            if(myFile.isDirectory()){
                for (File f : myFile.listFiles()){
                    copy(f.getAbsolutePath(), destination+"\\"+sourcePath.getFileName());
                }
            }
        } catch (Exception e) {
        } 
    }
    private void deleteFile(String path){
        try {
            File myFile = new File(path);
            if (myFile.isDirectory()){
                for (File f : myFile.listFiles()){
                    deleteFile(f.getAbsolutePath());
                }
            }
            myFile.delete();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private String listAllFiles(String path, int level){
        File myFile = new File(path);
        //kiem tra ton tai
        if (!myFile.exists()) return "";
        //Kiem tra file
        String result = "";
        for (int i = 0; i < level; i++) {
            result+="\t";
        }
        result = result + ((level==0?"":"|_") + myFile.getName()+"\n");
        if (myFile.isFile()) {
            return result;
        }
        //La thu muc
        for (File f : myFile.listFiles()){
            result += listAllFiles(f.getAbsolutePath(), level+1);
        }
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.getSystemLookAndFeelClassName();

        java.awt.EventQueue.invokeLater(() -> new QuanLyFile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButtonChoose;
    private javax.swing.JButton jButtonCopy;
    private javax.swing.JButton jButtonDetele;
    private javax.swing.JButton jButtonMove;
    private javax.swing.JButton jButtonRename;
    private javax.swing.JLabel jLabelFolder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldFolder;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
